<base href="/~jthollo/4820/projects/proj/"/>
<nav>
    <div class="nav-wrapper theme_bg">
        <a class="brand-logo">&nbsp;StudyBuddy</a>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-main" class="right hide-on-med-and-down">
            <li class="waves-effect waves-light"><a href="index.php">View Locations</a></li>
        </ul>
        <ul id="nav-mobile" class="side-nav">
            <li><a href="view.php">View Your Garage</a></li>
        </ul>
    </div>
</nav>
